USE tasker;

CREATE TABLE IF NOT EXISTS tasker.countries(
	id BIGINT PRIMARY KEY UNIQUE NOT NULL,
	country_code CHAR(2) NOT NULL UNIQUE,
	country_name VARCHAR(64) NOT NULL
);

INSERT INTO tasker.countries (id, country_code, country_name) VALUES
(1, 'AF', 'Afghanistan'),
(2, 'AX', 'Åland Islands'),
(3, 'AL', 'Albania'),
(4, 'DZ', 'Algeria'),
(5, 'AS', 'American Samoa'),
(6, 'AD', 'Andorra'),
(7, 'AO', 'Angola'),
(8, 'AI', 'Anguilla'),
(9, 'AQ', 'Antarctica'),
(10, 'AG', 'Antigua and Barbuda'),
(11, 'AR', 'Argentina'),
(12, 'AM', 'Armenia'),
(13, 'AW', 'Aruba'),
(14, 'AU', 'Australia'),
(15, 'AT', 'Austria'),
(16, 'AZ', 'Azerbaijan'),
(17, 'BS', 'Bahamas'),
(18, 'BH', 'Bahrain'),
(19, 'BD', 'Bangladesh'),
(20, 'BB', 'Barbados'),
(21, 'BY', 'Belarus'),
(22, 'BE', 'Belgium'),
(23, 'BZ', 'Belize'),
(24, 'BJ', 'Benin'),
(25, 'BM', 'Bermuda'),
(26, 'BT', 'Bhutan'),
(27, 'BO', 'Bolivia'),
(28, 'BQ', 'Bonaire, Sint Eustatius and Saba'),
(29, 'BA', 'Bosnia and Herzegovina'),
(30, 'BW', 'Botswana'),
(31, 'BV', 'Bouvet Island'),
(32, 'BR', 'Brazil'),
(33, 'IO', 'British Indian Ocean Territory'),
(34, 'BN', 'Brunei Darussalam'),
(35, 'BG', 'Bulgaria'),
(36, 'BF', 'Burkina Faso'),
(37, 'BI', 'Burundi'),
(38, 'CV', 'Cabo Verde'),
(39, 'KH', 'Cambodia'),
(40, 'CM', 'Cameroon'),
(41, 'CA', 'Canada'),
(42, 'KY', 'Cayman Islands'),
(43, 'CF', 'Central African Republic'),
(44, 'TD', 'Chad'),
(45, 'CL', 'Chile'),
(46, 'CN', 'China'),
(47, 'CX', 'Christmas Island'),
(48, 'CC', 'Cocos (Keeling) Islands'),
(49, 'CO', 'Colombia'),
(50, 'KM', 'Comoros'),
(51, 'CG', 'Congo'),
(52, 'CD', 'Congo (Democratic Republic)'),
(53, 'CK', 'Cook Islands'),
(54, 'CR', 'Costa Rica'),
(55, 'CI', 'Côte d’Ivoire'),
(56, 'HR', 'Croatia'),
(57, 'CU', 'Cuba'),
(58, 'CW', 'Curaçao'),
(59, 'CY', 'Cyprus'),
(60, 'CZ', 'Czechia'),
(61, 'DK', 'Denmark'),
(62, 'DJ', 'Djibouti'),
(63, 'DM', 'Dominica'),
(64, 'DO', 'Dominican Republic'),
(65, 'EC', 'Ecuador'),
(66, 'EG', 'Egypt'),
(67, 'SV', 'El Salvador'),
(68, 'GQ', 'Equatorial Guinea'),
(69, 'ER', 'Eritrea'),
(70, 'EE', 'Estonia'),
(71, 'SZ', 'Eswatini'),
(72, 'ET', 'Ethiopia'),
(73, 'FK', 'Falkland Islands'),
(74, 'FO', 'Faroe Islands'),
(75, 'FJ', 'Fiji'),
(76, 'FI', 'Finland'),
(77, 'FR', 'France'),
(78, 'GF', 'French Guiana'),
(79, 'PF', 'French Polynesia'),
(80, 'TF', 'French Southern Territories'),
(81, 'GL', 'Greenland'),
(82, 'GD', 'Grenada'),
(83, 'GP', 'Guadeloupe'),
(84, 'GU', 'Guam'),
(85, 'GT', 'Guatemala'),
(86, 'GG', 'Guernsey'),
(87, 'GN', 'Guinea'),
(88, 'GW', 'Guinea-Bissau'),
(89, 'GY', 'Guyana'),
(90, 'HT', 'Haiti'),
(91, 'HM', 'Heard Island and McDonald Islands'),
(92, 'VA', 'Holy See'),
(93, 'HN', 'Honduras'),
(94, 'HK', 'Hong Kong'),
(95, 'HU', 'Hungary'),
(96, 'IS', 'Iceland'),
(97, 'IN', 'India'),
(98, 'ID', 'Indonesia'),
(99, 'IR', 'Iran'),
(100, 'IQ', 'Iraq'),
(101, 'IE', 'Ireland'),
(102, 'IM', 'Isle of Man'),
(103, 'IL', 'Israel'),
(104, 'IT', 'Italy'),
(105, 'JM', 'Jamaica'),
(106, 'JP', 'Japan'),
(107, 'JE', 'Jersey'),
(108, 'JO', 'Jordan'),
(109, 'KZ', 'Kazakhstan'),
(110, 'KE', 'Kenya'),
(111, 'KI', 'Kiribati'),
(112, 'KP', 'Korea (Democratic People’s Republic)'),
(113, 'KR', 'Korea (Republic of)'),
(114, 'KW', 'Kuwait'),
(115, 'KG', 'Kyrgyzstan'),
(116, 'LA', 'Lao People’s Democratic Republic'),
(117, 'LV', 'Latvia'),
(118, 'LB', 'Lebanon'),
(119, 'LS', 'Lesotho'),
(120, 'LR', 'Liberia'),
(121, 'LY', 'Libya'),
(122, 'LI', 'Liechtenstein'),
(123, 'LT', 'Lithuania'),
(124, 'LU', 'Luxembourg'),
(125, 'MO', 'Macao'),
(126, 'MG', 'Madagascar'),
(127, 'MW', 'Malawi'),
(128, 'MY', 'Malaysia'),
(129, 'MV', 'Maldives'),
(130, 'ML', 'Mali'),
(131, 'MT', 'Malta'),
(132, 'MH', 'Marshall Islands'),
(133, 'MQ', 'Martinique'),
(134, 'MR', 'Mauritania'),
(135, 'MU', 'Mauritius'),
(136, 'YT', 'Mayotte'),
(137, 'MX', 'Mexico'),
(138, 'FM', 'Micronesia'),
(139, 'MD', 'Moldova'),
(140, 'MC', 'Monaco'),
(141, 'MN', 'Mongolia'),
(142, 'ME', 'Montenegro'),
(143, 'MS', 'Montserrat'),
(144, 'MA', 'Morocco'),
(145, 'MZ', 'Mozambique'),
(146, 'MM', 'Myanmar'),
(147, 'NA', 'Namibia'),
(148, 'NR', 'Nauru'),
(149, 'NP', 'Nepal'),
(150, 'NL', 'Netherlands'),
(151, 'NC', 'New Caledonia'),
(152, 'NZ', 'New Zealand'),
(153, 'NI', 'Nicaragua'),
(154, 'NE', 'Niger'),
(155, 'NG', 'Nigeria'),
(161, 'NU', 'Niue'),
(162, 'NF', 'Norfolk Island'),
(163, 'MK', 'North Macedonia'),
(164, 'MP', 'Northern Mariana Islands'),
(165, 'NO', 'Norway'),
(166, 'OM', 'Oman'),
(167, 'PK', 'Pakistan'),
(168, 'PW', 'Palau'),
(169, 'PS', 'Palestine, State of'),
(170, 'PA', 'Panama'),
(171, 'PG', 'Papua New Guinea'),
(172, 'PY', 'Paraguay'),
(173, 'PE', 'Peru'),
(174, 'PH', 'Philippines'),
(175, 'PN', 'Pitcairn'),
(176, 'PL', 'Poland'),
(177, 'PT', 'Portugal'),
(178, 'PR', 'Puerto Rico'),
(179, 'QA', 'Qatar'),
(180, 'RE', 'Réunion'),
(181, 'RO', 'Romania'),
(182, 'RU', 'Russian Federation'),
(183, 'RW', 'Rwanda'),
(184, 'BL', 'Saint Barthélemy'),
(185, 'SH', 'Saint Helena'),
(186, 'KN', 'Saint Kitts and Nevis'),
(187, 'LC', 'Saint Lucia'),
(188, 'MF', 'Saint Martin (French part)'),
(189, 'PM', 'Saint Pierre and Miquelon'),
(190, 'VC', 'Saint Vincent and the Grenadines'),
(191, 'WS', 'Samoa'),
(192, 'SM', 'San Marino'),
(193, 'ST', 'Sao Tome and Principe'),
(194, 'SA', 'Saudi Arabia'),
(195, 'SN', 'Senegal'),
(196, 'RS', 'Serbia'),
(197, 'SC', 'Seychelles'),
(198, 'SL', 'Sierra Leone'),
(199, 'SG', 'Singapore'),
(200, 'SX', 'Sint Maarten (Dutch part)'),
(201, 'SK', 'Slovakia'),
(202, 'SI', 'Slovenia'),
(203, 'SB', 'Solomon Islands'),
(204, 'SO', 'Somalia'),
(205, 'ZA', 'South Africa'),
(206, 'GS', 'South Georgia and the South Sandwich Islands'),
(207, 'SS', 'South Sudan'),
(208, 'ES', 'Spain'),
(209, 'LK', 'Sri Lanka'),
(210, 'SD', 'Sudan'),
(211, 'SR', 'Suriname'),
(212, 'SJ', 'Svalbard and Jan Mayen'),
(213, 'SE', 'Sweden'),
(214, 'CH', 'Switzerland'),
(215, 'SY', 'Syrian Arab Republic'),
(216, 'TW', 'Taiwan'),
(217, 'TJ', 'Tajikistan'),
(218, 'TZ', 'Tanzania'),
(219, 'TH', 'Thailand'),
(220, 'TL', 'Timor-Leste'),
(221, 'TG', 'Togo'),
(222, 'TK', 'Tokelau'),
(223, 'TO', 'Tonga'),
(224, 'TT', 'Trinidad and Tobago'),
(225, 'TN', 'Tunisia'),
(226, 'TR', 'Türkiye'),
(227, 'TM', 'Turkmenistan'),
(228, 'TC', 'Turks and Caicos Islands'),
(229, 'TV', 'Tuvalu'),
(230, 'UG', 'Uganda'),
(231, 'UA', 'Ukraine'),
(232, 'AE', 'United Arab Emirates'),
(233, 'GB', 'United Kingdom'),
(234, 'US', 'United States'),
(235, 'UM', 'United States Minor Outlying Islands'),
(236, 'UY', 'Uruguay'),
(237, 'UZ', 'Uzbekistan'),
(238, 'VU', 'Vanuatu'),
(239, 'VE', 'Venezuela'),
(240, 'VN', 'Vietnam'),
(241, 'VG', 'Virgin Islands (British)'),
(242, 'VI', 'Virgin Islands (U.S.)'),
(243, 'WF', 'Wallis and Futuna'),
(244, 'EH', 'Western Sahara'),
(245, 'YE', 'Yemen'),
(246, 'ZM', 'Zambia'),
(247, 'ZW', 'Zimbabwe');
